### ISSUE TITLE
关于调用ConvertBitmapToTextureTile()函数存在的问题。

### ISSUE THREAD

**Issue by LQJ-HNYY** [Aperture-Electronic/CTextureTile#1]
调用ConvertBitmapToTextureTile函数的时候，在此函数里面打印出strlen(pTextureTile)，同时输出(x,y)坐标点
![Uploading M~RZI[Y([9WKLTQ2T)19~77.png…]()
前期输出还是正常的，strlen的长度会增加
但是到一定数量之后，strlen的数量就不会增加固定在一个值，请问这个是什么原因？
![Uploading Y`{7`UU9HF16F[L6B)D%1V8.png…]()

**Comment by LQJ-HNYY** [comment]
补充上面的三张图片：
![1](https://user-images.githubusercontent.com/58969294/226570220-5228138d-5a87-45a3-85c7-217998c8b629.png)
![2](https://user-images.githubusercontent.com/58969294/226570318-a748258b-bc73-42c0-b8e0-9d1877d1134b.png)
![3](https://user-images.githubusercontent.com/58969294/226570336-ee20fe8d-d4f3-4025-8227-48a10f8027c5.png)

**Comment by LQJ-HNYY** [comment]
我输入图片是256x256的时候没问题，但是图片尺寸到了512x512就会出现这个错误。

**Comment by Aperture-Electronic** [comment]
C语言中的strlen函数的实现方式是：从开始计数，直到遇到第一个'\0'(即0x00)，所以，它不能拿来统计一个uint8_t* 数组的长度（因为数组中的值有可能为0x00）。
若要得到pTextureTile的长度，您可以使用offset指针ttOffset的值。

**Comment by LQJ-HNYY** [comment]
谢谢大佬！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Aperture-Electronic/CTextureTile"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月21日(星期二) 晚上6:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Aperture-Electronic/CTextureTile] 关于调用ConvertBitmapToTextureTile()函数存在的问题。 (Issue #1)





 
C语言中的strlen函数的实现方式是：从开始计数，直到遇到第一个'\0'(即0x00)，所以，它不能拿来统计一个uint8_t* 数组的长度（因为数组中的值有可能为0x00）。
 若要得到pTextureTile的长度，您可以使用offset指针ttOffset的值。
